### ISSUE TITLE
Invalid format when I run Infer task

### ISSUE THREAD

**Issue by AnakinPt** [mooltiverse/nyx-github-action#5]
When I run the nyx action in my pipeline, I get this error:
`time="2024-01-08T15:12:00Z" level=warning msg="the resume flag has been set and the state file has been configured but no state file exists at the given location /github/workspace/build/.nyx-state.yml. The state file will not be resumed."
time="2024-01-08T15:12:01Z" level=info msg="Version: '1.2.0+commit.2df79.branch.protobuf'"
branch           = protobuf
bump             = minor
core version     = false
latest version   = true
new release      = false
new version      = true
scheme           = SEMVER
timestamp        = 1704726720206
current version  = 1.2.0+commit.2df79.branch.protobuf
previous version = v1.1.78
prime version    = v1.1.78
Error: Unable to process file command 'output' successfully.
Error: Invalid format '1.2.0+commit.2df79.branch.protobuf'`

My nyx action is: 
    - name: Nyx infer
      id: nyx
      uses: mooltiverse/nyx-github-action@main

I'm running this action because I need the output from it to use the version in the following commands, like docker to use as a tag.

**Comment by flelli** [comment]
Hi @AnakinPt ,

it seems the Action breaks because of the version value `1.2.0+commit.2df79.branch.protobuf`. I need to investigate this

**Comment by AnakinPt** [comment]
Hi @flelli

This might be a problem with end-of-line. I would suggest, first, to strip the EOL character from the end of the version.
I got this same error with that cause. I just stripped it and worked.

Now, I'm using nyx, but with the gradle task and not the action anymore. But this is a problem that might appear to someone else.

**Comment by flelli** [comment]
Hi @AnakinPt , should be fixed now.
Can you give it a try?
